// Auto-generated by Kadmium. Do not edit manually.
// Use @Kadmium.gen_skip:<name> and @Kadmium.gen_continue:<name> to protect blocks.

import { Model, ModelHookContext, ModelConfig } from "../../model/init";
import { PUBLIC_TYPE_SYMBOL, RELATIONS_SYMBOL } from "../../repo/symbols";
import { ToOneRelation, ToManyRelation } from "../../repo/types/relations";
import { KadmiumRefinementCtx } from "../../validation/types/refinement";
import { User } from "../schemas/User";

export type RevisionSensitiveFields = never;

export type RevisionPublic = Revision;

type __RevisionRelations = {
	changed_by: ToOneRelation<User>;
};

export class Revision extends Model {
	static readonly _collection = "revision";
	_meta: "generated-schema" = "generated-schema";
	[PUBLIC_TYPE_SYMBOL]!: RevisionPublic;
	[RELATIONS_SYMBOL]!: __RevisionRelations;

	id!: number;
	target_table!: string;
	target_id!: string;
	data!: any | null;
	changed_fields!: string | null;
	changed_at!: Date | null;
	changed_by!: string | null;
// @Kadmium.gen_skip:conf
	_conf_: ModelConfig<this> = {
		hooks: {
			beforeCreate: [
				(ctx) => {
					// TODO: implement beforeCreate
				},
			],
			afterCreate: [],
			beforeUpdate: [],
			afterUpdate: [],
			beforeDelete: [],
			afterDelete: [],
			beforeRead: [],
			afterRead: [],
		},
		validation: {
			rules: [
				{ name: "example", refine: (data: this, ctx) => {
					// TODO: implement refine function
				}},
			],
		},
		features: [],
	};
	// @Kadmium.gen_continue:conf
}
