// Auto-generated by Kadmium. Do not edit manually.
// Use @Kadmium.gen_skip:<name> and @Kadmium.gen_continue:<name> to protect blocks.

import { Model, ModelHookContext, ModelConfig } from "../../model/index.js";
import { PUBLIC_TYPE_SYMBOL, RELATIONS_SYMBOL } from "../../repo/symbols.js";
import { ToOneRelation, ToManyRelation } from "../../repo/types/relations.js";
import { KadmiumRefinementCtx } from "../../validation/types/refinement.js";
import { AuditFeature, RevisionsFeature } from "../../features/index.js";
import { User } from "./User.js";
import { Post_tag } from "./Post_tag.js";
import { Comment } from "./Comment.js";

export type PostSensitiveFields = never;

export type PostPublic = Post;

type __PostRelations = {
	author: ToOneRelation<User>;
	comments: ToManyRelation<Comment>;
	post_tags: ToManyRelation<Post_tag>;
};

export class Post extends Model {
	static readonly _collection = "post";
	_meta: "generated-schema" = "generated-schema";
	[PUBLIC_TYPE_SYMBOL]!: PostPublic;
	[RELATIONS_SYMBOL]!: __PostRelations;

	id!: number;
	title!: string;
	content!: string | null;
	is_published!: boolean | null;
	author_id!: string;
	published_at!: Date | null;
	created_at!: Date | null;
	updated_at!: Date | null;
	// @Kadmium.gen_skip:conf
	_conf_: ModelConfig<this> = {
		hooks: {
			beforeCreate: [
				(ctx) => {
					// TODO: implement beforeCreate
				},
			],
			afterCreate: [],
			beforeUpdate: [],
			afterUpdate: [],
			beforeDelete: [],
			afterDelete: [],
			beforeRead: [],
			afterRead: [],
		},
		validation: {
			rules: [
				{
					name: "example", refine: (data: this, ctx) => {
						// TODO: implement refine function
					}
				},
			],
		},
		features: [AuditFeature, RevisionsFeature],
	};
	// @Kadmium.gen_continue:conf
}
